name: Get latest V8 stable version

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [master]
    paths:
      - "get_version_v8.py"
      - "get_version_chromium.py"
      - ".github/workflows/get_version.yml"

jobs:
  version_finder_v8:
    name: Get V8 version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: |
          cd $GITHUB_WORKSPACE
          pip install pandas
          version=$(python ./get_version_v8.py)

          if [ $? -eq 0 ]; then
            git pull
            echo $version > V8_VERSION
            
            if ( git update-index -q --refresh && git diff-index --quiet HEAD -- ); then
              echo "V8 version is already up to date"
              exit 0
            fi

            git config --global user.name 'V8 version finder'
            git config --global user.email 'v8_version_finder@localhost'
            git commit -am "Update V8_VERSION to $version"
            git push
          else
            echo "Failed to retrieve V8 version"
            exit 1
          fi

  version_finder:
    name: Get Chromium version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: |
          cd $GITHUB_WORKSPACE
          pip install pandas
          version=$(python ./get_version_chromium.py)

          if [ $? -eq 0 ]; then
            git pull
            echo $version > CHROMIUM_VERSION
            
            if ( git update-index -q --refresh && git diff-index --quiet HEAD -- ); then
              echo "V8 version is already up to date"
              exit 0
            fi

            git config --global user.name 'Chromium version finder'
            git config --global user.email 'chromium_version_finder@localhost'
            git commit -am "Update CHROMIUM_VERSION to $version"
            git push
          else
            echo "Failed to retrieve Chromium version"
            exit 1
          fi
